import type { Metadata } from "next";
import SidebarBarDashboard from "@/components/layout/SidebarBarDashboard";
import DashboardHeader from "@/components/layout/DashboardHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AccountLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="min-h-full flex flex-row">
      <SidebarBarDashboard />
      <main className="ml-64">
        <DashboardHeader />
        {children}
      </main>
    </div>
  );
}
